author: "eran@zimbler.net"
description: "Stately is a commandline multiplatform tool for handling projects that contains several repositories."
filesets:
  includes:
  - README.md
  - LICENSE
  excludes:
  - \.git
  - .*\.go
  depth: 3
settings:
  targetdir: "."
  outfiles: ['stately']
  build: go install -v
